---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-components-flux
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
    # tag: v0.2.0
  url: https://github.com/sundarok/cluster-components-flux-kustomize.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: components
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/sundarok/clusters-flux.git
  include:
    - repository:
        name: cluster-components-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: components
  namespace: flux-system
spec:
  interval: 1m
  path: alpaca/components/
  prune: true
  sourceRef:
    kind: GitRepository
    name: components
  dependsOn:
    - name: flux-system
  patches:
    patch:
      patches:
        - patch: |
            - op: add
              path: /metadata/labels/myowner2
              value: "my-pods2"
          target:
            kind: Deployment